version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APPID=3000
    ports:
      - "3000"
    restart: always

  nginx:
    image: arm64v8/nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "1337:1337"
    healthcheck:
      test: ["systemctl", "status", "nginx"]
      interval: 2s
      timeout: 30s
      retries: 5
      start_period: 5s
    restart: always
    depends_on:
      - api
    
  haproxy:
    image: arm64v8/haproxy
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    restart: always
    depends_on:
      - nginx

